<?php
/**
 * Root Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');   
    $categoryId = 2;
    $_category = Mage::getModel('catalog/category')->load($categoryId);
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div id="content-wrapper" class="store">
    <div class="store-banner">
        <div class="image-text-content container">
            <div class="row">
                <div class="col-md-12">
                    <!-- <img src="images/content/store-banner.jpg" alt="store banner"> -->
                    <div class="caption">                        
                        <!-- <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name'); ?></h1> -->
                        <!-- <p><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p> -->

                        <?php //echo $this->getMessagesBlock()->toHtml() ?>

                        <?php //if(//$_imgUrl): ?>
                            <?php //echo $_imgHtml ?>
                        <?php //endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="image-text-content container">
            <div class="row">
                <div class="col-md-12">
                    <div class="side-bar">
                        <h1>REFINE BY</h1><a href="#" class="clear-all">Clear All</a>
                        <hr class="small">
                        
                        <div class="each-filter-section">
                            <div class="all-inputs">
                                <div class="each-input">
                                    <input type="checkbox" name="product_category">
                                    <label class="checkbox-label" for="product_category">
                                        <span></span><p class="label-text">New</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="product_category">
                                    <label class="checkbox-label" for="product_category">
                                        <span></span><p class="label-text">Featured</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="product_category">
                                    <label class="checkbox-label" for="product_category">
                                        <span></span><p class="label-text">Best Selling</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="product_category">
                                    <label class="checkbox-label" for="product_category">
                                        <span></span><p class="label-text">Promotion</p>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="each-filter-section">
                            <div class="title">
                                <a href="#collections" class="load-more">
                                    <h2>Collections</h2><i class="fa fa-chevron-up"></i>
                                </a>
                                <div class="clear"></div>
                            </div>
                            
                            <div id="collections" class="all-inputs">
                                <div class="each-input">
                                    <input type="checkbox" name="collection_type">
                                    <label class="checkbox-label" for="collection_type">
                                        <span></span><p class="label-text">Artisan Selection</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="collection_type">
                                    <label class="checkbox-label" for="collection_type">
                                        <span></span><p class="label-text">Gourmet Selection</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="collection_type">
                                    <label class="checkbox-label" for="collection_type">
                                        <span></span><p class="label-text">Grand Cru Collection</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="collection_type">
                                    <label class="checkbox-label" for="collection_type">
                                        <span></span><p class="label-text">Flower Art</p>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="each-filter-section">
                            <div class="title">
                                <a href="#types" class="load-more">
                                    <h2>Types</h2><i class="fa fa-chevron-up"></i>
                                </a>
                                <div class="clear"></div>
                            </div>

                            <div id="types" class="all-inputs">
                                <div class="col-1">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Black</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Oolong</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Green</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">White</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Pu-Erh</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type"> 
                                            <span></span><p class="label-text">Yellow</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Rooibos</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Fruit Tea</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Herbal Tea</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_type">
                                        <label class="checkbox-label" for="product_type">
                                            <span></span><p class="label-text">Herbs</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>

                        <div class="each-filter-section">
                            <div class="title">
                                <a href="#region" class="load-more">
                                    <h2>Region</h2><i class="fa fa-chevron-up"></i>
                                    <div class="clear"></div>
                                </a>
                            </div>

                            <div id="region" class="all-inputs">
                                <div class="col-1">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Africa</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">America</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Argentina</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">China</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Egypt</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Europe</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Germany</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Indonesia</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Japan</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Mixed</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Morocco</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Nepal</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Sri Lanka</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Thailand</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Turkey</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Taiwan</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>

                        <div class="each-filter-section">
                            <div class="title">
                                <a href="#caffeine_lvl" class="load-more">
                                    <h2>caffeine level</h2><i class="fa fa-chevron-up"></i>
                                </a>
                                <div class="clear"></div>
                            </div>
                            
                            <div id="caffeine_lvl" class="all-inputs">
                                <div class="col-1">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_caffeine_level">
                                        <label class="checkbox-label" for="product_caffeine_level">
                                            <span></span><p class="label-text">Low</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_caffeine_level">
                                        <label class="checkbox-label" for="product_caffeine_level">
                                            <span></span><p class="label-text">Medium</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_caffeine_level">
                                        <label class="checkbox-label" for="product_caffeine_level">
                                            <span></span><p class="label-text">High</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_caffeine_level">
                                        <label class="checkbox-label" for="product_caffeine_level">
                                            <span></span><p class="label-text">Pamper</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_caffeine_level">
                                        <label class="checkbox-label" for="product_caffeine_level">
                                            <span></span><p class="label-text">Perk Up</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_caffeine_level">
                                        <label class="checkbox-label" for="product_caffeine_level">
                                            <span></span><p class="label-text">Unwind</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>

                        <div class="each-filter-section">
                            <div class="title">
                                <a href="#aroma" class="load-more">
                                    <h2>aroma</h2><i class="fa fa-chevron-up"></i>
                                </a>
                                <div class="clear"></div>
                            </div>

                            <div id="aroma" class="all-inputs">
                                <div class="col-1">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_aroma">
                                        <label class="checkbox-label" for="product_aroma">
                                            <span></span><p class="label-text">Citrus</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_aroma">
                                        <label class="checkbox-label" for="product_aroma">
                                            <span></span><p class="label-text">Floral</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_aroma">
                                        <label class="checkbox-label" for="product_aroma">
                                            <span></span><p class="label-text">Forest</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_aroma">
                                        <label class="checkbox-label" for="product_aroma">
                                            <span></span><p class="label-text">Fruity</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_aroma">
                                        <label class="checkbox-label" for="product_aroma">
                                            <span></span><p class="label-text">Marine</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_aroma">
                                        <label class="checkbox-label" for="product_aroma">
                                            <span></span><p class="label-text">Minty</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Plant</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Smokey</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Spicy</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Sweet</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Toasty</p>
                                        </label>
                                    </div>
                                    <div class="each-input">
                                        <input type="checkbox" name="product_region">
                                        <label class="checkbox-label" for="product_region">
                                            <span></span><p class="label-text">Woody</p>
                                        </label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>

                        <div class="each-filter-section">
                            <div class="title">
                                <a href="#proficiency" class="load-more">
                                    <h2>proficiency</h2><i class="fa fa-chevron-up"></i>
                                </a>
                                <div class="clear"></div>
                            </div>
                            
                            <div id="proficiency" class="all-inputs">
                                <div class="each-input">
                                    <input type="checkbox" name="proficiency_type">
                                    <label class="checkbox-label" for="proficiency_type">
                                        <span></span><p class="label-text">Apperentice</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="proficiency_type">
                                    <label class="checkbox-label" for="proficiency_type">
                                        <span></span><p class="label-text">Discoverer</p>
                                    </label>
                                </div>
                                <div class="each-input">
                                    <input type="checkbox" name="proficiency_type">
                                    <label class="checkbox-label" for="proficiency_type">
                                        <span></span><p class="label-text">Connoisseur</p>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="info">
                            <ul>
                                <li><a href="#"><i class="question"></i><span>Gryphon FAQ</span></a></li>
                                <li><a href="#"><i class="delivery-info"></i><span>Delivery Information</span></a></li>
                                <li><a href="#"><i class="tracking"></i><span>Track Delivery</span></a></li>
                            </ul>
                        </div>

                    </div>

                    <div class="all-products">
                        <?php
                            $_productCollection=$this->getLoadedProductCollection();
                            $_helper = $this->helper('catalog/output');    
                        ?>
                        <div class="controls">
                            <div class="item-count-wrapper">
                                <span class="item-count"><?php echo $_productCollection->count(); ?> items found</span>
                            </div>
                            <div class="sort-by">
                                <!-- <label for="sortby">Sort By:</label> -->
                                <ul>
                                    <li><a href="#">Price</a><div class="v-line"></div></li>
                                    <li><a href="#">Name</a><div class="v-line"></div></li>
                                    <li><a href="#">New item</a></li>
                                </ul>
                            </div>
                        </div>

                        <hr class="grey">

                        <div class="row">
                            <div class="col-md-12">    
                                <?php if(!$_productCollection->count()): ?>
                                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
                                <?php else: ?>
                                    <?php foreach ($_productCollection as $_product): ?>
                                        <div class="each-product">
                                            <div class="product-image">
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                    <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                                                            one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                                                            we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                                                            will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                                                            This $_imgSize value could even be decreased further, based on the page layout
                                                            (one column, two column, three column) and number of product columns. */ ?>
                                                    <?php $_imgSize = 300; ?>
                                                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                                         class="img-responsive img" />
                                                </a>
                                                <ul class="cta-list">
                                                    <li>
                                                        <a href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(500); ?>" class="fancybox"><img src="<?php echo $this->getSkinUrl('images/icons/magnifying-glass.png') ?>" alt="magnifying glass"></a>
                                                    </li>                                                    
                                                    <li>
                                                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>                                    
                                                            <a href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><img src="<?php echo $this->getSkinUrl('images/icons/plus-sign.png') ?>" alt="plus sign"></a>
                                                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                                            <a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/icons/plus-sign.png') ?>" alt="plus sign"></a>
                                                        <?php else: ?>
                                                            <!-- <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p> -->
                                                        <?php endif; ?>                                                        
                                                    </li>
                                                </ul>
                                            </div>        
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-caption">        
                                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                                <h4><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h4>
                                                <p><?php echo $this->getLayer()->getCurrentCategory()->getName() ?></p>
                                                <p class="price"><?php echo $this->getPriceHtml($_product, true) ?></p>
                                            </a>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; 

                                // Provides a block where additional page components may be attached, primarily good for in-page JavaScript
                                if ($this->getChild('after')) {
                                    $_afterChildren = $this->getChild('after')->getSortedChildren();
                                    foreach ($_afterChildren as $_afterChildName) {
                                        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
                                        //set product collection on after blocks
                                        $_afterChild->setProductCollection($_productCollection);
                                        echo $_afterChild->toHtml();
                                    }
                                }
                                ?>             
                            </div>
                        </div>
                        <!-- </div> -->
                        <div class="row load-more-wrapper">
                            <div class="col-md-12">
                                <div class="each-load-more">
                                    <hr class="load-more">
                                </div>
                                <div class="each-load-more">
                                    <a href="#" class="load-more-btn">load more</a>
                                </div>
                                <div class="each-load-more">
                                    <hr class="load-more">
                                </div>
                            </div>
                        </div>
                          
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>