	<div id="mobile-footer-wrapper" class="visible-xs visible-sm">
		
		<div id="mobile-header-footer-copy" class="mobile-footer">
			<h2>newsletter sign up</h2>
			<hr class="small">
			<p>Join our Gryphon Tea Family and be the first to learn about our latest news, and enjoy exclusive deals and invites to events</p>

			<div class="search">
				<input type="text" name="search" placeholder="Enter your email address" />
				<button class="signup"><i class="fa fa-check"></i> <span>Sign up</span></button>
			</div>

			<hr class="dotted">

			<h2>FOLLOW US</h2>
			<hr class="small">
			<ul class="share-ctas">
				<li><a href="https://instagram.com/gryphontea/" target="_blank" class="instagram"></a></li>
				<li><a href="https://www.pinterest.com/gryphontea/" target="_blank" class="pintrest"></a></li>
				<li><a href="https://www.facebook.com/gryphonteacompany" target="_blank" class="facebook"></a></li>
				<li><a href="https://www.linkedin.com/company/gryphon-tea-company" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
				<li><a href="https://www.youtube.com/channel/UCrKNQcT3PHO-o_vQBMUlH8Q" target="_blank" class="youtube"><i class="fa fa-youtube"></i></a></li>
				<li><a href="https://plus.google.com/+Gryphonteacompany/posts" target="_blank" class="google-plus"><i class="fa fa-google-plus"></i></a></li>
			</ul>

			<div class="copywrite">
				<h6>&copy; 2013 GRYPHON TEA COMPANY.</h6>
				<p>All material on this site is copyrighted by Gryphon Tea Company. Gryphon Tea Company® is a registered trademark. No images or copy on this site may be used without written permission by Gryphon Tea Company.</p>	
			</div>

		</div>
				
	</div>

	<div id="footer-wrapper" class="visible-md visible-lg fixed-footer"><!-- container-fluid -->
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h2>newsletter sign up</h2>
					<hr class="small">
					<p>Join our Gryphon Tea Family and be the first to learn about our latest news, and enjoy exclusive deals and invites to events</p>

					<div class="search">
						<input type="text" name="search" placeholder="Enter your email address" />
						<button class="signup"><i class="fa fa-check"></i> <span>Sign up</span></button>
					</div>
				</div>
				<div class="col-md-7">
					<div class="links-wrapper">
						<div class="about-us-links links">
							<h2>about us</h2>
							<hr class="small">
							<ul>
								<li><a href="<?php echo $this->getUrl('faq'); ?>">FAQ</a></li>															
								<li><a href="<?php echo $this->getUrl('our-story');?>">Our Story</a></li>
								<li><a href="http://test.gryphontea.com/magento/wp">Blog</a></li>
								<li><a href="<?php echo $this->getUrl('careers');?>">Careers</a></li>
								<li><a href="<?php echo $this->getUrl('trade'); ?>">Trade</a></li>
								<li><a href="<?php echo $this->getUrl('discover-tea'); ?>">Discover Tea</a></li>								
								<li><a href="<?php echo $this->getUrl('contact-us'); ?>">Contact Us</a></li>															
							</ul>
						</div>
						<div class="store-links links">
							<h2>tea store</h2>
							<hr class="small">
							<ul>
								<?php $store_category = Mage::getModel('catalog/category')->loadByAttribute('name', 'Store'); ?>
								<li><a href="<?php echo $store_category->getUrl(); ?>">TEA</a></li>
								<?php $pantry_products = Mage::getModel('catalog/category')->loadByAttribute('name', 'Pantry'); ?>
								<li><a href="<?php echo $pantry_products->getUrl(); ?>">Pantry</a></li>
								<?php $gifts_products = Mage::getModel('catalog/category')->loadByAttribute('name', 'gifts');	?>
								<?php $gifts_products_data = $gifts_products->getData(); ?>
								<li><a href="<?php echo $this->getUrl($gifts_products_data['url_path']); ?>">Gifts</a></li>
								<li><a href="<?php echo $this->getUrl('store-locator'); ?>">Store Locator</a></li>
							</ul>
						</div>
						<div class="selections-links links">
							<h2>Collections</h2>
							<hr class="small">
							<?php 
							// $collection_category = Mage::getModel('catalog/category')->loadByAttribute('name', 'Collections');

							/*Returns comma separated ids*/
							// $subcats = $collection_category->getChildren();			
							?>
							<?php 
							$collection_categories = Mage::getModel('catalog/category')->loadByAttribute('name', 'Collections')->getChildrenCategories();							
							?>
							<ul>
								<?php foreach($collection_categories as $collection_category):
										$_category = Mage::getModel('catalog/category')->load($collection_category->getId());
										$caturl     = $_category->getURL();
										$catname     = $_category->getName();
										$catdesc     = $_category->getDescription();
										$catimgurl     = $_category->getImageUrl(); ?>									
										<li><a href="<?php echo $caturl; ?>"><?php echo $catname; ?></a></li>								
								<?php endforeach; ?>
							</ul>
						</div>
						<div class="customer-service-link links">
							<h2>Order Information</h2>
							<hr class="small">
							<ul>
								<li><a href="<?php echo Mage::getUrl('customer/account/create'); ?>">Account Registration</a></li>
								<li><a href="<?php echo $this->getUrl('rewards'); ?>">Rewards Program</a></li>
								<li><a href="<?php echo $this->getUrl('shipping-info'); ?>">Shipping Information</a></li>
								<li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
								<li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms & Conditions</a></li>
								<li><a href="http://www.trackntrace.com.sg/">Track Order</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<h2>FOLLOW US</h2>
					<hr class="small">
					<ul class="share-ctas">
						<li><a href="https://instagram.com/gryphontea/" target="_blank" class="instagram"></a></li>
						<li><a href="https://www.pinterest.com/gryphontea/" target="_blank" class="pintrest"></a></li>
						<li><a href="https://www.facebook.com/gryphonteacompany" target="_blank" class="facebook"></a></li>
						<li><a href="https://www.linkedin.com/company/gryphon-tea-company" target="_blank" class="linkedin"><i class="fa fa-linkedin" style="
"></i></a></li>
						<li><a href="https://www.youtube.com/channel/UCrKNQcT3PHO-o_vQBMUlH8Q" target="_blank" class="youtube"><i class="fa fa-youtube" style="
"></i></a></li>
						<li><a href="https://plus.google.com/+Gryphonteacompany/posts" target="_blank" class="google-plus"><i class="fa fa-google-plus" style="
"></i></a></li>
					</ul>
					<h2>STORE LOCATOR</h2>
					<hr class="small">
					<ul class="store-locator-links">
						<li><a href="<?php echo $this->getUrl('store-locator'); ?>?location=central">Central</a></li>
						<li><a href="<?php echo $this->getUrl('store-locator'); ?>?location=east">East</a></li>
						<li><a href="<?php echo $this->getUrl('store-locator'); ?>?location=west">West</a></li>						
					</ul>
					<ul class="store-locator-links">
						<li><a href="<?php echo $this->getUrl('store-locator'); ?>?location=north">North</a></li>
						<li><a href="<?php echo $this->getUrl('store-locator'); ?>?location=south">South</a></li>
					</ul>
				</div>
			</div>
		</div>

	</div>
	<div id="copyright-wrapper" class="visible-md visible-lg fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>&copy; 2013 GRYPHON TEA COMPANY.</p>
					<p>All material on this site is copyrighted by Gryphon Tea Company. Gryphon Tea Company® is a registered trademark. No images or copy on this site may be used without written permission by Gryphon Tea Company.</p>	
				</div>
			</div>
		</div>
	</div>
</div><!-- page wrapper end -->