<?php
$count = $this->helper('checkout/cart')->getSummaryCount();
$quote = Mage::getModel('checkout/session')->getQuote();
$quoteData= $quote->getData();
?>
<div id="mobile-header-wrapper" class="visible-xs visible-sm">
	<header id="main-mobile-header">

		<div id="mobile-marquee-container">
			<p>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
			</p>

		</div>
		<div id="mobile-fixed-container">
			<div class="mobile-menu-button"></div>
			<a href="#" class="mobile-menu-logo"></a>

			<div class="mobile-menu-icon-button-container">
				<div class="mobile-menu-icon-button mobile-search-button"></div>
				<div class="mobile-menu-icon-button mobile-cart-button">
					<span><?php echo $count; ?></span>
				</div>
			</div>

		</div>
		<div id="mobile-search-expand-container">
			<form id="search_mini_form">
				<?php echo $this->getChildHtml('topSearch') ?>
			</form>
		</div>
		<div id="mobile-cart-expand-container">
			<div class="cart-preview-select">
				<h5><img src="<?php echo $this->getSkinUrl('images/icons/cart.png'); ?>" alt=""> SHOPPING CART</h5>
				<?php 
					$cart = Mage::getModel('checkout/cart')->getQuote();
					$cartQty = $this->helper('checkout/cart')->getSummaryCount();
					$cartTotal = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
				?>
				<?php if ($cartQty>0): ?>							        
					    
					<ul class="cart-header">
						<li>PRODUCT</li>
						<li>QTY</li>
						<li>SUB TOTAL</li>
					</ul>
					
					<?php								
					foreach ($cart->getAllItems() as $item) {
					    $productName = $item->getProduct()->getName();
					    $productPrice = $item->getProduct()->getPrice();
					    $productQty = $item->getQty();
					    $priceInclVat = $item->getRowTotalInclTax();
					    $productImage = Mage::helper('catalog/image')->init($item->getProduct(), 'thumbnail');
					    
					?>
					<ul class="cart-content">							
						<li><img src="<?php echo $productImage; ?>" alt=""><span><?php echo $productName; ?></span></li>
						<li><?php echo $productQty; ?></li>
						<li><?php echo Mage::helper('core')->currency($priceInclVat, true, false); ?></li>
					</ul>
					<?php
					}
					?>
					<ul class="cart-summary">								
				        <?php if ($cartQty==1): ?>
				            <?php echo '<li><span class="total-items">1 ITEM</span></li>'; ?>
				        <?php else: ?>
				            <?php echo '<li><span class="total-items">'.$cartQty.' ITEMS</span></li>'; ?>
				        <?php endif; ?>
				        <li><span class="sub-total">SUB TOTAL</span></li>									
				        <li><span class="sub-total-amount"><?php echo Mage::helper('core')->currency($cartTotal, true, false); ?></span></li>							
					</ul>

					<div class="cta-btns">
						<a href="<?php echo $this->getUrl('store');?>" class="continue-shopping"><button type="button" class="cta button"><span><span>Back to Shopping</span></span></button></a>
      						<a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="shopping-cart"><button type="button" class="cta button"><span><span>Shopping Cart</span></span></button></a>
					</div>
				<?php else: ?>
					<p>Your cart is empty. <a href="<?php echo $this->getUrl('checkout/cart'); ?>">Click here to go to cart anyway.</a></p>
				<?php endif; ?>
			</div>
		</div>
		


		<div id="mobile-expand-container">

			<div id="mobile-account">
				<div id="mobile-account-header">
					<?php 
					$session = Mage::getSingleton('customer/session');
					if($session->isLoggedIn()) {
					   $customer = $session->getCustomer();
					   // echo $customer->getName();
					   $customer_name = $customer->getFirstname();
					}
					?>						
					<p><a href="#" class="account name"><?php echo (isset($customer_name)) ? 'Welcome, '.$customer_name : $this->__('Account'); ?></a></p>
					<div id="mobile-account-expand-button"></div>
				</div>
				
				<ul>
					<li><a href="">account information</a></li>
					<li><a href="">address book</a></li>
					<li><a href="">order history</a></li>
					<li><a href="">gift card</a></li>
					<li><a href="">reward points</a></li>
					<li><a href="">refer friend</a></li>
				</ul>
				
			</div> <!-- mobile-account -->

			<div class="mobile-submenu">
				<div class="mobile-submenu-header">Gryphon Store</div>
				<ul>
					<li class="has-sub-menu">
						<a href="#">Tea</a>
						<ul class="sub-menu">
				      <li><a href="store.html">Black</a></li>
				      <li><a href="store.html">White</a></li>
				      <li><a href="store.html">Green</a></li>
				      <li><a href="store.html">Yellow</a></li>
				      <li><a href="store.html">Oolong</a></li>
				      <li><a href="store.html">Pu-erh</a></li>
				      <li><a href="store.html">Rooibos</a></li>
				      <li><a href="store.html">Tisane</a></li>
				      <li><a href="store.html">Herbs</a></li>
				    </ul>
					</li>
					<li><a href="#">Pantry</a></li>
					<li class="has-sub-menu">
						<a href="#">Gifts</a>
						<ul class="sub-menu">
							<li><a href="#">Gift Card</a></li>
							<li><a href="#">Treasure Tin</a></li>
						</ul>
					</li>
					<li><a href="#">Subscription</a></li>
					<li><a href="#">Trade</a></li>
				</ul>
			</div>

			<div class="mobile-submenu">
				<div class="mobile-submenu-header">About Gryphon</div>
				<ul>
					<li><a href="">Collections</a></li>
					<li><a href="">Blog</a></li>
					<li><a href="">Discover tea</a></li>
					<li><a href="">Our story</a></li>
					<li><a href="">Careers</a></li>
				</ul>
			</div>

			<div class="mobile-submenu">
				<div class="mobile-submenu-header">Customer Service</div>
				<ul>
					<li><a href="">contact us</a></li>
					<li><a href="">faq &amp; help</a></li>
					<li><a href="">shipping information</a></li>
					<li><a href="">track order</a></li>
					<li><a href="">terms &amp; conditions</a></li>
					<li><a href="">privacy policy</a></li>
				</ul>
			</div>

			<div class="extra-space"></div>
			<div id="mobile-header-footer-copy" class="mobile-footer">
				<h2>newsletter sign up</h2>
				<hr class="small">
				<p>By signing up the Gryphon newsletter, be the first one to hear about our special offers, new arrivals, latest news and trends and other events.</p>

				<div class="search">
					<input type="text" name="search" placeholder="Enter your email address" />
					<button class="signup"><i class="fa fa-check"></i> <span>Sign up</span></button>
				</div>

				<hr class="dotted">

				<h2>FOLLOW US</h2>
				<hr class="small">
				<ul class="share-ctas">
					<li><a href="#" class="instagram"></a></li>
					<li><a href="#" class="pintrest"></a></li>
					<li><a href="#" class="twitter"></a></li>
					<li><a href="#" class="facebook"></a></li>
				</ul>

				<div class="copywrite">
					<h6>&copy; 2013 GRYPHON TEA COMPANY.</h6>
					<p>All material on this site is copyrighted by Gryphon Tea Company. Gryphon Tea Company® is a registered trademark. No images or copy on this site may be used without written permission by Gryphon Tea Company.</p>	
				</div>

			</div>
		
		</div> <!-- mobile-expand-container -->
	</header>
</div>
<div id="header-wrapper" class="visible-md visible-lg"><!-- container-fluid -->
	<header id="main-header" class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="logo-wrapper hidden-xs hidden-sm visible-md visible-lg">
					<a href="<?php echo $this->getUrl('') ?>" class="site-logo">
						<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>">
					</a>
				</div>
				<div id="menu-wrapper">
					<?php 
						$currentUrl = Mage::helper('core/url')->getCurrentUrl();
						$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
						$path = $url->getPath();

						if (strpos($path,'checkout') === false) {
							echo $this->getChildHtml('topMenu');
						}
					?>
				</div>	
				<div id="header-cta">
					<div class="promo-image-text">
						<!-- <div class="promo hidden-xs hidden-sm">							
							<p>Get <span class="red">10%</span> off discount from your first purchase <br>until 17th of Jan with Promo Code: <span class="red">SHOPNOW</span></p>
						</div> -->

						<div class="cta">
							<ul class="cta-list">
								<li>
									<a href="#" class="currency"><span class="hidden-xs hidden-sm"><i class="fa fa-dollar"></i>Currency</span></a>									
								</li>
								<li>
									<a href="#" class="search"><span class="hidden-xs hidden-sm">Search</span></a>									
								</li>
								<?php 
								$session = Mage::getSingleton('customer/session');
								if($session->isLoggedIn()) {
								   $customer = $session->getCustomer();
								   // echo $customer->getName();
								   $customer_name = $customer->getFirstname();
								}
								?>						
								<li><a href="#" class="account"><span class="hidden-xs hidden-sm"><?php echo (isset($customer_name)) ? $customer_name	 : $this->__('Account'); ?></span></a></li>
								<li class="hidden-md hidden-lg"><hr class="divider"></li>
                                <?php if ($count) :?>
                                <li><a href="#" class="cart"><span><?php echo Mage::helper('core')->currency($quoteData['subtotal']); ?> (<?php echo $count; ?>)</span></a></li>
                            	<?php else: ?>
                            	<li><a href="#" class="cart"><span><?php echo $this->__('CART'); ?></span></a></li>
                                <?php endif; ?>
							</ul>
						</div>
						<?php if($session->isLoggedIn()): ?>
							<ul class="account-select">
								<li><a href="<?php echo Mage::getUrl('customer/account'); ?>">My Account</a></li>
								<li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">Log Out</a></li>
							</ul>
						<?php else: ?>
							<ul class="account-select">
								<li><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">Log In</a></li>
								<li><a href="<?php echo Mage::getUrl('customer/account/create'); ?>">Register</a></li>							
							</ul>
						<?php endif; ?>
						<div class="cart-preview-select">
							<h5><img src="<?php echo $this->getSkinUrl('images/icons/cart.png'); ?>" alt=""> SHOPPING CART</h5>
							<?php 
								$cart = Mage::getModel('checkout/cart')->getQuote();
								$cartQty = $this->helper('checkout/cart')->getSummaryCount();
								$cartTotal = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
							?>
							<?php if ($cartQty>0): ?>							        
								    
								<ul class="cart-header">
									<li>PRODUCT</li>
									<li>QTY</li>
									<li>SUB TOTAL</li>
								</ul>
								
								<?php								
								foreach ($cart->getAllItems() as $item) {
								    $productName = $item->getProduct()->getName();
								    $productPrice = $item->getProduct()->getPrice();
								    $productQty = $item->getQty();
								    $priceInclVat = $item->getRowTotalInclTax();
								    $productImage = Mage::helper('catalog/image')->init($item->getProduct(), 'thumbnail');
								    
								?>
								<ul class="cart-content">							
									<li><img src="<?php echo $productImage; ?>" alt=""><span><?php echo $productName; ?></span></li>
									<li><?php echo $productQty; ?></li>
									<li><?php echo Mage::helper('core')->currency($priceInclVat, true, false); ?></li>
								</ul>
								<?php
								}
								?>
								<ul class="cart-summary">								
							        <?php if ($cartQty==1): ?>
							            <?php echo '<li><span class="total-items">1 ITEM</span></li>'; ?>
							        <?php else: ?>
							            <?php echo '<li><span class="total-items">'.$cartQty.' ITEMS</span></li>'; ?>
							        <?php endif; ?>
							        <li><span class="sub-total">SUB TOTAL</span></li>									
							        <li><span class="sub-total-amount"><?php echo Mage::helper('core')->currency($cartTotal, true, false); ?></span></li>							
								</ul>

								<div class="cta-btns">
									<a href="<?php echo $this->getUrl('store');?>" class="continue-shopping"><button type="button" class="cta button"><span><span>Back to Shopping</span></span></button></a>
            						<a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="shopping-cart"><button type="button" class="cta button"><span><span>Shopping Cart</span></span></button></a>
								</div>
							<?php else: ?>
								<p>Your cart is empty. <a href="<?php echo $this->getUrl('checkout/cart'); ?>">Click here to go to cart anyway.</a></p>
							<?php endif; ?>
							
						</div>
						<?php echo $this->getChildHtml('topSearch') ?>
			            <?php echo $this->getChildHtml('currency_top') ?>			            
					</div>
				</div>
			</div>
		</div>
	</header>
</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plugins/gryphon/jquery.gryphon-mobile-header.js'); ?>"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$("#main-mobile-header").gryphon_mobile_header();
	});
</script>