<div class="subscription-form" id="content-wrapper">

	<div class="subscription-banner">
		  <div class="image-text-content container">
			<div class="row">
			  <div class="col-md-12 caption-container">
				<div class="caption">
				  <h1>Gourmet Selection</h1>
				</div>
			  </div>
			</div>
		  </div>
		</div>

		<div class="main-content">

			<div class="first-content">

				<div class="banner-text">
				  <div class="text-content container">
					<div class="row">
					  <div class="col-md-12">
						<h1>Gourmet Curation</h1>
						

						<hr class="small">

						<div class="row">
						  <div class="col-md-8 col-md-offset-2">
							<p>We choose for you, three teas from our expansive Gourmet Selection that allow you to explore new frontiers of flavour, or perhaps welcome familiar favourites, all delivered conveniently to your door every month.</p>
						  </div>
						</div>
					  </div>
					</div>
				  </div>
				</div>

			  </div>

			<div class="second-content">

				<div class="image-text-content container">
					<div class="row">
						<div class="col-md-12">
							<div class="table-1">
								<h1>plans in singapore</h1>
								<hr class="small">
								
								<div class="table-responsive">
									<table class="table">								  	
								      	<tbody>
										<?php
										$_helper = $this->helper('catalog/output'); 
										$artisanSingaporeCollection = Mage::getModel('subscriptions/subscriptions')->getGourmetSingaporeSubscriptions();	
										//echo count($artisanSingaporeCollection->getData());exit;								
										$cnt = 1;
										foreach($artisanSingaporeCollection->getData() as $productsing):
											$_productId = $productsing['entity_id'];
											$_productsingpur = Mage::getModel('catalog/product')->load($_productId);
											
											$nameStart = substr($_helper->productAttribute($_productsingpur, $_productsingpur->getName() , 'name'), 0,2);
											$monthtext = ' MONTHS';
											if($cnt == 1)
											{
												$monthtext = ' MONTH';
										
												$equivalent = ($_productsingpur->getPrice()/1);
											}else if($cnt == 2)
											{										
												$equivalent = ($_productsingpur->getPrice()/3);
											}else if($cnt == 3)
											{										
												$equivalent = ($_productsingpur->getPrice()/6);
											}else
											{										
												$equivalent = ($_productsingpur->getPrice()/12);
											}
											
										?>
									        <tr>
											<?php if(count($artisanSingaporeCollection->getData()) == $cnt){
												?>
												<td class="col-1"><div class="certificate-icon"></div><div class="certificate-text"><h3><?php echo $nameStart.$monthtext ?><br><span>SGP Subscription</span></h3></div></td>
												<?php 
											}else{
												?>
												<td class="col-1"><h3><?php echo $nameStart.$monthtext ?><br><span>SGP Subscription</span></h3></td>
												<?php 
											}
											?>
									          	
									          	<td class="col-2"><p><?php echo $_helper->productAttribute($_productsingpur, $_productsingpur->getShortDescription() , 'short_description'); ?></p></td>
									          	<td class="col-3"><h3><?php echo Mage::helper('core')->currency($_productsingpur->getPrice(),true,false); ?><br><span>shipping included</span></h3></td>
									          	<td class="col-4"><p>Equivalent to <br> <?php echo Mage::helper('core')->currency($equivalent,true,false); ?> per month</p></td>
												
									          	<td class="col-5"><a class="add-to-cart-btn" href="javascript:;" onclick="setLocation('<?php echo $this->getAddToCartUrl($_productsingpur) ?>');"><i class="fa fa-plus"></i><span>Add to Cart</span></a></td>
									        </tr>
											
											
									       <?php 
										   $cnt++;
										   endforeach; ?>
										   
								      	</tbody>
									</table>
								</div>
								<div class="terms-icon"></div>
								<div class="terms">
									<p>Customers who sign-up for a 1 year subscription can get a 10% discount off on all other online purchases throughout the subscription period.</p>
									<p>Not applicable with other special promotions or discounts.</p>


								</div>
							</div>

							<div class="table-2">
								<h1>international plans</h1>
								<hr class="small">
								
								<div class="table-responsive">
									<table class="table">	

								      	<tbody>
									       <?php
										
										$artisanSingaporeIntCollection = Mage::getModel('subscriptions/subscriptions')->getGourmetInternationalSubscriptions();	
										//echo count($artisanSingaporeCollection->getData());exit;								
										$cnt = 1;
										foreach($artisanSingaporeIntCollection->getData() as $productsingint):
											$_productIdInt = $productsingint['entity_id'];
											$_productsingpurint = Mage::getModel('catalog/product')->load($_productIdInt);
											
											$nameStart = substr($_helper->productAttribute($_productsingpurint, $_productsingpurint->getName() , 'name'), 0,2);
											$monthtext = ' MONTHS';
											if($cnt == 1)
											{
												$monthtext = ' MONTH';
										
												$equivalent = ($_productsingpurint->getPrice()/1);
											}else if($cnt == 2)
											{										
												$equivalent = ($_productsingpurint->getPrice()/3);
											}else if($cnt == 3)
											{										
												$equivalent = ($_productsingpurint->getPrice()/6);
											}else
											{										
												$equivalent = ($_productsingpurint->getPrice()/12);
											}
											
										?>
									        <tr>
											<?php if(count($artisanSingaporeCollection->getData()) == $cnt){
												?>
												<td class="col-1"><div class="certificate-icon"></div><div class="certificate-text"><h3><?php echo $nameStart.$monthtext ?><br><span>SGP Subscription</span></h3></div></td>
												<?php 
											}else{
												?>
												<td class="col-1"><h3><?php echo $nameStart.$monthtext ?><br><span>SGP Subscription</span></h3></td>
												<?php 
											}
											?>
									          	
									          	<td class="col-2"><p><?php echo $_helper->productAttribute($_productsingpurint, $_productsingpurint->getShortDescription() , 'short_description'); ?></p></td>
									          	<td class="col-3"><h3><?php echo Mage::helper('core')->currency($_productsingpurint->getPrice(),true,false); ?><br><span>shipping included</span></h3></td>
									          	<td class="col-4"><p>Equivalent to <br> <?php echo Mage::helper('core')->currency($equivalent,true,false); ?> per month</p></td>
									          	<td class="col-5"><a class="add-to-cart-btn" href="javascript:;" onclick="setLocation('<?php echo $this->getAddToCartUrl($_productsingpurint) ?>');"><i class="fa fa-plus"></i><span>Add to Cart</span></a></td>
									        </tr>
											
									       <?php 
										   $cnt++;
										   endforeach; ?>
								      	</tbody>
									</table>
								</div>
								<div class="terms-icon"></div>
								<div class="terms">
									<p>Customers who sign-up for a 1 year subscription can get a 10% discount off on all other online purchases throughout the subscription period.</p>
									<p>Not applicable with other special promotions or discounts.</p>
								</div>
							</div>


							<div class="last-content">
								<h1>WHAT YOU GET</h1>
								<hr class="small">
								
								<div class="all-products">
									<div class="row">
										<div class="col-md-12">									
											<div class="each-product">
												<a href="product.html">													
													<img alt="product" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/gryphon/gryphon_theme/images/content/subscription/gourmet-subscription-1.jpg">
												</a>		
												<a class="product-caption" href="product.html">
													<h4>THE TEA</h4>
													<!-- <p>Peruse and personalise the 30 silken sachets that will be delivered each month. </p>													 -->
													<p>Three gourmet teas carefully selected from our portfolio of blends, provided with a guide to ideal preparation and the perfect pairing.</p>													
												</a>
											</div>
										
											<div class="each-product">
												<a href="product.html">
													<img alt="product" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/gryphon/gryphon_theme/images/content/subscription/gourmet-subscription-2.jpg">
												</a>		
												<a class="product-caption" href="product.html">
													<!-- <h4>THE FLEXIBILITY</h4> -->
													<h4>THE SURPRISE</h4>
													<!-- <p>Let us know by the 17th of the month if you wish to make a change to your selection, and it will be ready for your next delivery. </p>													 -->
													<p>We slip in an occasional special gift or include a unique blend not yet available to our regular customers.</p>
												</a>
											</div>
										
											<div class="each-product">
												<a href="product.html">
													<img alt="product" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/gryphon/gryphon_theme/images/content/subscription/gourmet-subscription-3.jpg">
												</a>		
												<a class="product-caption" href="product.html">
													<h4>THE EXTRAS</h4>
													<!-- <p>With a one-year subscription, you receive 10% off all other regularly priced online orders.</p> -->
													<p>With a one-year subscription, you receive 10% off all other regularly priced online orders.</p>
													<p class="terms">Not applicable with other special promotions or discounts.</p>
												</a>
											</div>
										
											<div class="each-product">
												<a href="product.html">													
													<img alt="product" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/gryphon/gryphon_theme/images/content/subscription/gourmet-subscription-4.jpg">
												</a>		
												<a class="product-caption" href="product.html">
													<h4>THE DELIVERY</h4>
													<p>Order by the 17th of each month and have your tea shipped from our warehouse promptly on the 23rd, or the next available business day, along with tracking information sent via email.</p>													
												</a>
											</div>
										</div>
									</div>									
								</div>
				
							</div>
						</div>
					</div>
				</div>

			</div>
			
		</div>

	</div>
	
	<script>

	/*
	$('.add').on('click',function(e){
		e.preventDefault();
    var $qty=$(this).closest('p').find('.qty');
    var currentVal = parseInt($qty.text());
    if (!isNaN(currentVal)) {
        $qty.text(currentVal + 1);
    }
  });
  $('.minus').on('click',function(e){
  	e.preventDefault();
	  var $qty=$(this).closest('p').find('.qty');
	  var currentVal = parseInt($qty.text());
	  if (!isNaN(currentVal) && currentVal > 0) {
	      $qty.text(currentVal - 1);
	  }
  });
	*/

	var initialLoad = true;
	jQuery(document).ready(function(){		
	    jQuery(window).on('scroll', function() {
	        var scrollPos = jQuery(window).scrollTop();
	        
	        if( ( scrollPos != 0 ) ) {
	            console.log('scrolling')
	            jQuery('#header-wrapper').addClass('shadow');
	        }       
	        else if( ( scrollPos === 0 ) ) {
	            jQuery('#header-wrapper').removeClass('shadow');
	        }
	    });

	    initialLoad = false;
	});
	</script>