<?php
/**
 * Miragedesign Web Development
 *
 * @category    Miragedesign
 * @package     Miragedesign_Checkoutcustomiser
 * @copyright   Copyright (c) 2011 Miragedesign (http://miragedesign.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<form id="co-billing-form" action="">
    <div class="col2-set row">
        <div class="col-1 col-md-6 billing_address">
        <h1><?php echo $this->__('Billing Address')?></h1>
        <hr class="small" />

            <ul class="form-list">
            <?php if ($this->customerHasAddresses()): ?>
                <li class="wide each-input dropdown-address">
                    <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box dropdown">
                        <?php //echo $this->getAddressesHtmlSelect('billing') ?>
                        <div id="custAddress">
                        <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
                        <?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
                        <?php $data = array();?>
                            <select name="billing_address_id" id="billing-address-select" class="address-select" title="">                                
                                <option value="">New Address</option>                                                                                       
                                <?php $i=0; foreach ($customer->getAddresses() as $address):?>                                
                                    <?php $data = $address->toArray();?>
                                    <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>                                    
                                    <option <?php if($i==0): ?>selected="selected"<?php endif; ?> value="<?php echo $data['entity_id']; ?>"><?php echo $data['firstname'] . ' ' . $data['firstname'] . ', ' . $data['street'] . ', ' . $data['city'] . ', ' . $data['postcode']. ', ' . $country_name;  ?></option>
                                <?php $i++; endforeach; ?>  
                            </select>
                         </div>                        
                    </div>
                </li>
            <?php endif; ?>
            <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
                <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
                <ul>
                    <li class="fields">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')
                            ->setTemplate('miragedesign/customer/widget/name.phtml')
                            ->toHtml()
                        ?>
                    </li>
                    <li class="fields">
                        <div class="field each-input">
                            <label for="billing:company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                            </div>
                        </div>
            <?php if(!$this->isCustomerLoggedIn()): ?>
                        <div class="field each-input">
                            <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                            </div>
                        </div>
            <?php endif; ?>
                    </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="fields each-input">
                        <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="fields each-input">
                        <label></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php endfor; ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <li class="fields each-input">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field each-input">
                            <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                            </div>
                        </div>
                        <div class="field each-input">
                            <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field each-input">
                            <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="dropdown">
                                <?php echo $this->getCountryHtmlSelect('billing') ?>
                            </div>
                        </div>
                        <div class="field each-input">
                            <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box dropdown">
                                <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field each-input">
                            <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                            </div>
                        </div>
                        <div class="field each-input">
                            <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                            </div>
                        </div>
                    </li>
                    <?php if(!$this->isCustomerLoggedIn()): ?>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if (false && ($_dob->isEnabled() || $_gender->isEnabled())): // we don't need these fields in checkout steps ?>
                    <li class="fields">
                    <?php if ($_dob->isEnabled()): ?>
                        <div class="field each-input">
                            <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <div class="field each-input">
                            <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </div>
                    <?php endif ?>
                    </li>
                <?php endif ?>

                <?php if ($this->isTaxvatEnabled()):?>
                    <li><?php echo $this->getTaxvatHtml() ?></li>
                <?php endif; ?>

                    <li class="fields" id="register-customer-password">
                        <div class="field each-input">
                            <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                            </div>
                        </div>
                        <div class="field each-input">
                            <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                            </div>
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    <?php endif; ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                            <label for="billing:save_in_address_book" class="checkbox-label">
                                <span></span><p class="label-text"><?php echo $this->__('Save in address book') ?></p>
                            </label>
                        </li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
             </li>
            </ul>
            <?php if (!$this->canShip()): ?>
                <input type="hidden" name="billing[use_for_shipping]" value="1" />
            <?php endif; ?>

        </div>
        <div class="col-2 col-md-5 col-md-offset-1">
            <h1><?php echo $this->__('Shipping Address')?></h1>
            <hr class="small" />

            <ul class="form-list">
            <?php if ($this->customerHasAddresses()): ?>
               <li class="wide each-input dropdown-address">
                   <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
                   <div class="input-box dropdown">
                       <?php //echo $this->getAddressesHtmlSelect('shipping') ?>
                       <div id="custAddress">
                        <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
                        <?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
                        <?php $data = array();?>
                            <select name="shipping_address_id" id="shipping-address-select" class="address-select" title="">                                
                                <option value="">New Address</option>                                                                                       
                                <?php $i=0; foreach ($customer->getAddresses() as $address):?>                                
                                    <?php $data = $address->toArray();?>
                                    <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>                                    
                                    <option <?php if($i==0): ?>selected="selected"<?php endif; ?> value="<?php echo $data['entity_id']; ?>"><?php echo $data['firstname'] . ' ' . $data['firstname'] . ', ' . $data['street'] . ', ' . $data['city'] . ', ' . $data['postcode']. ', ' . $country_name;  ?></option>
                                <?php $i++; endforeach; ?>  
                            </select>
                         </div>  
                   </div>
               </li>
            <?php endif ?>
                <li class="control same-as-billing">
                    <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" />
                    <label class="checkbox-label" for="shipping:same_as_billing">
                        <span></span><p class="label-text"><?php echo $this->__('If shipping address is same as billing address, tick here.') ?></p>
                    </label>
                </li>
                <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                    <ul>
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')
                                ->setTemplate('miragedesign/customer/widget/name.phtml')
                                ->toHtml()
                            ?>
                        </li>
                        <li class="fields">
                            <div class="fields each-input">
                                <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                                <div class="input-box">
                                    <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="fields each-input">
                            <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="fields each-input">
                            <label></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                <?php endfor; ?>
                        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="fields each-input">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                        <?php endif; ?>
                        <li class="fields">
                            <div class="field each-input">
                                <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                            <div class="field each-input">
                                <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field each-input">
                                <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                <div class="dropdown">
                                    <?php echo $this->getCountryHtmlSelect('shipping') ?>
                                </div>
                            </div>
                            <div class="field each-input">
                                <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                <div class="input-box dropdown">
                                    <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                    //]]>
                                    </script>
                                    <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field each-input">
                                <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                <div class="input-box">
                                    <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                            <div class="field each-input">
                                <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                                <div class="input-box">
                                    <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </li>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                            <label for="shipping:save_in_address_book" class="checkbox-label">
                                <span></span><p class="label-text"><?php echo $this->__('Save in address book') ?></p>
                            </label>
                        </li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <input type="hidden" name="md_shipping_method" id="md_shipping_method" value="" />
</form>
    <div class="row">
        <div class="col-1 col-md-6"></div>
        <div class="col-2 col-md-5 col-md-offset-1">
            <div id="billing_shipping">
                <div class="delivery-rates">
                    <h2><?php echo $this->__('DELIVERY'); ?></h2>
                    <div class="table-responsive">
                        <table id="delivery-rate-tbl" class="table">
                            <thead>
                            <tr>
                                <th>COUNTRY</th>
                                <th>ESTIMATED DELIVERY TIME</th>
                                <th>FLAT RATE (SGD)</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><p class="country">Singapore</p></td>
                                <td><p class="delivery_time">2 to 3 working days</p></td>
                                <td><p class="flat_rate">S$ 6.00</p></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <p>All local orders are delivered with registered postage.</p>
                    <p>All products are shipped directly from Singapore. Please allow 5 to 7 working days on top of the estimated delivery time for us to process your order.</p>
                    <p>Please expect slight delays for orders shipped during peak seasons. <br />
                        <span>— Chinese New Year, Christmas etc.</span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="buttons-set row action-container" id="billing-buttons-container">
        <!-- <p class="required"><?php echo $this->__('* Required Fields') ?></p> -->
        <div class="back-link col-md-4">
            <a class="cta back-btn" href="<?php echo $this->getUrl('/'); ?>"><i class="fa fa-chevron-left"></i> <?php echo $this->__('go back to continue shopping') ?></a>
        </div>
        <div class="col-md-3 col-md-offset-5">
            <button type="button" title="<?php echo $this->__('Continue') ?>" class="button continue cta" onclick="billing.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span class="please-wait" id="billing-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
            </span>
        </div>
    </div>

<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    var GetBillingAddressUrl = '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/';

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new CustomRegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }

	var shipping = new Customshipping('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
	var shippingForm = new VarienForm('co-billing-form');
	shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
	//shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
	$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

	var shippingRegionUpdater = new CustomRegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>