<div id="page-wrapper">
	<div id="header-wrapper" class=""><!-- container-fluid -->
		<header id="main-header" class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="logo-wrapper hidden-xs hidden-sm visible-md visible-lg">
						<a href="index.html" class="site-logo"><img src="images/logo/main-logo.png" alt="logo"></a>
					</div>
					<div id="menu-wrapper">
						
					</div>	
					<div id="header-cta">
						<div class="promo-image-text">
							<div class="promo hidden-xs hidden-sm">
								<img src="images/icons/header-img-1.png" class="promo-img" alt="header img">
								<p>Get <span class="red">10%</span> off discount from your first purchase <br>until 17th of Jan with Promo Code: <span class="red">SHOPNOW</span></p>
							</div>

							<div class="cta">
								<ul class="cart-cta-list">
									<li><a href="#"><i class="question"></i><span>Gryphon FAQ</span></a></li>
									<li><a href="#"><i class="delivery-info"></i><span>Delivery Information</span></a></li>
									<li><a href="#"><i class="tracking"></i><span>Track Delivery</span></a></li>
								</ul>
								<!-- <ul class="cta-list">
									<li><a href="#" class="search"><span class="hidden-xs hidden-sm">Search</span></a></li>									
									<li><a href="account.html" class="account"><span class="hidden-xs hidden-sm">Richard</span></a></li>
									<li class="hidden-md hidden-lg"><hr class="divider"></li>
									<li><a href="cart.html" class="cart"><span>$S 36.50 (2)</span></a></li>
								</ul> -->
							 </div>
						</div>
					</div>
				</div>
			</div>
		</header>
	</div>
