<div id="page-wrapper">
	<div id="header-wrapper" class=""><!-- container-fluid -->
		<header id="main-header" class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="logo-wrapper hidden-xs hidden-sm visible-md visible-lg">
						<a href="index.html" class="site-logo"><img src="images/logo/main-logo.png" alt="logo"></a>
					</div>
					<div id="menu-wrapper">
						<nav id="nav-main">
							<ul class="main-menu hidden-xs hidden-sm">
								<li>
									<a href="store.html">TEA <i class="fa fa-chevron-down"></i></a>
									<ul class="sub-menu">
										<li><a href="store.html">Black</a></li>
										<li><a href="store.html">White</a></li>
										<li><a href="store.html">Green</a></li>
										<li><a href="store.html">Yellow</a></li>
										<li><a href="store.html">Oolong</a></li>
										<li><a href="store.html">Pu-erh</a></li>
										<li><a href="store.html">Rooibos</a></li>
										<li><a href="store.html">Tisane</a></li>
										<li><a href="store.html">Herbs</a></li>
									</ul>
								</li>
								<li>
									<a href="teawear.html">TEAWARE</a>
								</li>
								<li>
									<a href="gifts.html">GIFTS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="subscription.html">SUBSCRIPTION</a>
								</li>
								<li>
									<a href="collections.html">COLLECTIONS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="blog.html">BLOG</a>
								</li>
								<li>
									<a href="trade.html">TRADE</a>
								</li>
							</ul>
							<i class="fa fa-bars icon-font mobile-menu-btn hidden-md hidden-lg"></i>
							<ul class="mobile-menu hidden-md hidden-lg">
								<li>
									<a href="#">TEA</a>
									<ul class="sub-menu">
										<li><a href="store.html">Black</a></li>
										<li><a href="store.html">White</a></li>
										<li><a href="store.html">Green</a></li>
										<li><a href="store.html">Yellow</a></li>
										<li><a href="store.html">Oolong</a></li>
										<li><a href="store.html">Pu-erh</a></li>
										<li><a href="store.html">Rooibos</a></li>
										<li><a href="store.html">Tisane</a></li>
										<li><a href="store.html">Herbs</a></li>
									</ul>
								</li>
								<li>
									<a href="teawear.html">TEAWARE</a>
								</li>
								<li>
									<a href="gifts.html">GIFTS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="subscription.html">SUBSCRIPTION</a>
								</li>
								<li>
									<a href="collections.html">COLLECTIONS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="blog.html">BLOG</a>
								</li>
								<li>
									<a href="trade.html">TRADE</a>
								</li>
							</ul>
						</nav>
					</div>	
					
				</div>
			</div>
		</header>
	</div>
