

<div id="mobile-header-wrapper" class="visible-xs visible-sm">
	<header id="main-mobile-header">

		<div id="mobile-marquee-container">
			<!--
			<p>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</p>
			-->
			<p>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
				<span>Get 10% off discount from your first purchase until 17th of jan with promo code: shopnow</span>
			</p>

		</div>
		<div id="mobile-fixed-container">
			<div class="mobile-menu-button"></div>
			<a href="#" class="mobile-menu-logo"></a>

			<div class="mobile-menu-icon-button-container">
				<div class="mobile-menu-icon-button mobile-search-button"></div>
				<div class="mobile-menu-icon-button mobile-cart-button">
					<span>0</span>
				</div>
			</div>


		</div>

		<div id="mobile-search-expand-container">
			<form id="search_mini_form">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</form>
		</div>
		<div id="mobile-cart-expand-container">
			<div class="cart-preview-select">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
		</div>


		<div id="mobile-expand-container">

			<div id="mobile-account">
				<div id="mobile-account-header">
					<p>Welcome, <span class="name">Richard</span></p>
					<div id="mobile-account-expand-button"></div>
				</div>
				
				<ul>
					<li><a href="">account information</a></li>
					<li><a href="">address book</a></li>
					<li><a href="">order history</a></li>
					<li><a href="">gift card</a></li>
					<li><a href="">reward points</a></li>
					<li><a href="">refer friend</a></li>
				</ul>
				
			</div> <!-- mobile-account -->

			<div class="mobile-submenu">
				<div class="mobile-submenu-header">Gryphon Store</div>
				<ul>
					<li class="has-sub-menu">
						<a href="#">Tea</a>
						<ul class="sub-menu">
				      <li><a href="store.html">Black</a></li>
				      <li><a href="store.html">White</a></li>
				      <li><a href="store.html">Green</a></li>
				      <li><a href="store.html">Yellow</a></li>
				      <li><a href="store.html">Oolong</a></li>
				      <li><a href="store.html">Pu-erh</a></li>
				      <li><a href="store.html">Rooibos</a></li>
				      <li><a href="store.html">Tisane</a></li>
				      <li><a href="store.html">Herbs</a></li>
				    </ul>
					</li>
					<li><a href="#">Pantry</a></li>
					<li class="has-sub-menu">
						<a href="#">Gifts</a>
						<ul class="sub-menu">
							<li><a href="#">Gift Card</a></li>
							<li><a href="#">Treasure Tin</a></li>
						</ul>
					</li>
					<li><a href="#">Subscription</a></li>
					<li><a href="#">Trade</a></li>
				</ul>
			</div>

			<div class="mobile-submenu">
				<div class="mobile-submenu-header">About Gryphon</div>
				<ul>
					<li><a href="">Collections</a></li>
					<li><a href="">Blog</a></li>
					<li><a href="">Discover tea</a></li>
					<li><a href="">Our story</a></li>
					<li><a href="">Careers</a></li>
				</ul>
			</div>

			<div class="mobile-submenu">
				<div class="mobile-submenu-header">Customer Service</div>
				<ul>
					<li><a href="">contact us</a></li>
					<li><a href="">faq &amp; help</a></li>
					<li><a href="">shipping information</a></li>
					<li><a href="">track order</a></li>
					<li><a href="">terms &amp; conditions</a></li>
					<li><a href="">privacy policy</a></li>
				</ul>
			</div>

			<div class="extra-space"></div>
			<div id="mobile-header-footer-copy" class="mobile-footer">
				<h2>newsletter sign up</h2>
				<hr class="small">
				<p>By signing up the Gryphon newsletter, be the first one to hear about our special offers, new arrivals, latest news and trends and other events.</p>

				<div class="search">
					<input type="text" name="search" placeholder="Enter your email address" />
					<button class="signup"><i class="fa fa-check"></i> <span>Sign up</span></button>
				</div>

				<hr class="dotted">

				<h2>FOLLOW US</h2>
				<hr class="small">
				<ul class="share-ctas">
					<li><a href="#" class="instagram"></a></li>
					<li><a href="#" class="pintrest"></a></li>
					<li><a href="#" class="twitter"></a></li>
					<li><a href="#" class="facebook"></a></li>
				</ul>

				<div class="copywrite">
					<h6>&copy; 2013 GRYPHON TEA COMPANY.</h6>
					<p>All material on this site is copyrighted by Gryphon Tea Company. Gryphon Tea Company® is a registered trademark. No images or copy on this site may be used without written permission by Gryphon Tea Company.</p>	
				</div>

			</div>

			




 


		</div> <!-- mobile-expand-container -->
	</header>
</div> <!-- mobile-header-wrapper -->


<div id="page-wrapper">
	<div id="header-wrapper" class="visible-md visible-lg"><!-- container-fluid -->
		<header id="main-header" class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="logo-wrapper hidden-xs hidden-sm visible-md visible-lg">
						<a href="index.html" class="site-logo"><img src="images/logo/main-logo.png" alt="logo"></a>
					</div>
					<div id="menu-wrapper">
						<nav id="nav-main">
							<ul class="main-menu hidden-xs hidden-sm">
								<li>
									<a href="store.html">TEA <i class="fa fa-chevron-down"></i></a>
									<ul class="sub-menu">
										<li><a href="store.html">Black</a></li>
										<li><a href="store.html">White</a></li>
										<li><a href="store.html">Green</a></li>
										<li><a href="store.html">Yellow</a></li>
										<li><a href="store.html">Oolong</a></li>
										<li><a href="store.html">Pu-erh</a></li>
										<li><a href="store.html">Rooibos</a></li>
										<li><a href="store.html">Tisane</a></li>
										<li><a href="store.html">Herbs</a></li>
									</ul>
								</li>
								<li>
									<a href="teawear.html">TEAWARE</a>
								</li>
								<li>
									<a href="gifts.html">GIFTS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="subscription.html">SUBSCRIPTION</a>
								</li>
								<li>
									<a href="collections.html">COLLECTIONS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="blog.html">BLOG</a>
								</li>
								<li>
									<a href="trade.html">TRADE</a>
								</li>
							</ul>
							<i class="fa fa-bars icon-font mobile-menu-btn hidden-md hidden-lg"></i>
							<ul class="mobile-menu hidden-md hidden-lg">
								<li>
									<a href="#">TEA</a>
									<ul class="sub-menu">
										<li><a href="store.html">Black</a></li>
										<li><a href="store.html">White</a></li>
										<li><a href="store.html">Green</a></li>
										<li><a href="store.html">Yellow</a></li>
										<li><a href="store.html">Oolong</a></li>
										<li><a href="store.html">Pu-erh</a></li>
										<li><a href="store.html">Rooibos</a></li>
										<li><a href="store.html">Tisane</a></li>
										<li><a href="store.html">Herbs</a></li>
									</ul>
								</li>
								<li>
									<a href="teawear.html">TEAWARE</a>
								</li>
								<li>
									<a href="gifts.html">GIFTS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="subscription.html">SUBSCRIPTION</a>
								</li>
								<li>
									<a href="collections.html">COLLECTIONS <!-- <i class="fa fa-chevron-down"></i> --></a>
									<!-- <ul class="sub-menu">
										<li><a href=""></a></li>
									</ul> -->
								</li>
								<li>
									<a href="blog.html">BLOG</a>
								</li>
								<li>
									<a href="trade.html">TRADE</a>
								</li>
							</ul>
						</nav>
					</div>	
					
				</div>
			</div>
		</header>
	</div>


	<script type="text/javascript" src="js/plugins/gryphon/jquery.gryphon-mobile-header.js"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$("#main-mobile-header").gryphon_mobile_header();
		});
	</script>