<?php
/**
 * View Gift Card basic info
 */
?>

<?php $_customerGift = $this->getCustomerGift() ?>
<?php $_giftCard = $this->getGiftVoucher() ?>

<div class="box-account box-info">
    <div class="box-head visible-md-block visible-lg-block" >
        <h2><?php echo $this->__('Gift Card Code Information') ?></h2>
    </div>

    <div class="visible-md-block visible-lg-block">
        <ul class="form-list">
            <li class="fields">
                <div class="field custom-field">
                    <p><?php echo $this->__('Gift Card Code') ?></p>
                </div>
                <div class="field custom-field-right">
                    <a id="hidden_gift_card_code" href="#" onclick="viewFullGiftCode(); return false;" title="<?php echo $this->__('Gift Card Code') ?>"><?php echo $this->getCodeTxt($_giftCard) ?></a>
                    <input id="full_gift_card_code" type="text" class="input-text" value="<?php echo $_giftCard->getGiftCode() ?>" title="<?php echo $this->__('Gift Card Code') ?>" style="display: none;" onblur="hideGiftCode();" readonly="true" />
                    <script type="text/javascript">
                        function viewFullGiftCode() {
                            $('hidden_gift_card_code').hide();
                            $('full_gift_card_code').show();
                            $('full_gift_card_code').focus();
                        }
                        function hideGiftCode() {
                            $('hidden_gift_card_code').show();
                            $('full_gift_card_code').hide();
                        }
                    </script>
                </div>
            </li>
            <li class="fields">
                <div class="field custom-field">
                    <p><?php echo $this->__('Balance') ?><p>
                </div>
                <div class="field custom-field-right">
                    <?php echo $this->getBalanceFormat($_giftCard) ?>
                </div>
            </li>
        <?php if ($_giftCard->getDescription()): ?>
            <li class="fields">
                <div class="field custom-field">
                    <p><?php echo $this->__('Description') ?></p>
                </div>
                <div class="field custom-field-right">
                    <?php echo $_giftCard->getDescription() ?>
                </div>
            </li>
        <?php endif ?>
            <li class="fields">
                <div class="field custom-field">
                    <p><?php echo $this->__('Status') ?></p>
                </div>
                <div class="field custom-field-right">
                    <?php echo $this->getStatus($_giftCard) ?>
                </div>
            </li>
            <li class="fields">
                <div class="field custom-field">
                    <p><?php echo $this->__('Added Date') ?></p>
                </div>
                <div class="field custom-field-right">
                    <?php echo $this->formatDate($_customerGift->getData('added_date'), 'medium') ?>
                </div>
            </li>
    <!--        Hai.Tran-->
            <li class="fields">
                <div class="field custom-field">
                    <p><?php echo $this->__('Expired Date') ?></p>
                </div>
                <div class="field custom-field-right">
                    <?php 
                        //Hai.Tran
                        $expired_date = $_giftCard->getData('expired_at');
                        if(!$expired_date) echo $this->__('Permanent');
                        else echo $this->formatDate($expired_date, 'medium');
                    ?>
                    <?php //echo $this->formatDate($_giftCard->getData('expired_at'), 'medium') ?>
                </div>
            </li>
        <?php if ($this->checkSendFriendGiftCard($_giftCard)): ?>
            <li class="fields">
                <div class="field custom-field">
                    <strong><?php echo $this->__('Comment') ?></strong>
                </div>
                <div class="field custom-field-right">
                    <?php echo $this->__('This is your gift to give for %s (%s)',$_giftCard->getRecipientName(), $_giftCard->getRecipientEmail()) ?>
                </div>
            </li>
            <?php if ($_shipment = $this->getShipmentForGiftCard($_giftCard)): ?>
                <?php $tracks = $_shipment->getTracksCollection(); ?>
                <li class="fields">
                    <div class="field custom-field">
                        <strong><?php echo $this->__('Check Shipping') ?></strong>
                    </div>
                    <div class="field custom-field-right">
                        <div>
                            <a href="<?php echo $this->getUrl('sales/order/shipment', array('order_id' => $_shipment->getOrderId())) ?>" title="<?php echo $this->__('View Shipment') ?>"><?php echo $this->__('View Shipment') ?></a>
                            |
                            <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_shipment) ?>','trackshipment','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track the shipment') ?>"><?php echo $this->__('Track the shipment') ?></a>
                        </div>
                        <div>
                        <?php if ($_size = $tracks->count()): ?>
                            <?php echo $this->__('Tracking Number(s):') ?>
                            <?php
                            $i = 1;
                            foreach($tracks as $track): ?>
                            <?php if($track->isCustom()): ?>
                                <?php echo $this->escapeHtml($track->getNumber()) ?>
                            <?php else: ?>
                                <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?></a>
                            <?php endif; ?>
                            <?php if($i!=$_size): ?>, <?php endif; ?>
                            <?php $i++;
                            endforeach; ?>
                        <?php endif ?>
                        </div>
                    </div>
                </li>
            <?php endif ?>
        <?php endif ?>
        </ul>
    </div>

    <div class="visible-xs-block visible-sm-block">
        <div class="form-list">
            <div class="row">
                <div class="col-xs-6">

                    <div class="fields">
                        <div class="field custom-field">
                            <p><?php echo $this->__('Gift Card Code') ?></p>
                        </div>
                        <div class="field custom-field-right">
                            <a id="hidden_gift_card_code" href="#" onclick="viewFullGiftCode(); return false;" title="<?php echo $this->__('Gift Card Code') ?>"><?php echo $this->getCodeTxt($_giftCard) ?></a>
                            <input id="full_gift_card_code" type="text" class="input-text" value="<?php echo $_giftCard->getGiftCode() ?>" title="<?php echo $this->__('Gift Card Code') ?>" style="display: none;" onblur="hideGiftCode();" readonly="true" />
                            <script type="text/javascript">
                                function viewFullGiftCode() {
                                    $('hidden_gift_card_code').hide();
                                    $('full_gift_card_code').show();
                                    $('full_gift_card_code').focus();
                                }
                                function hideGiftCode() {
                                    $('hidden_gift_card_code').show();
                                    $('full_gift_card_code').hide();
                                }
                            </script>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="fields">
                        <div class="field custom-field">
                            <p><?php echo $this->__('Balance') ?><p>
                        </div>
                        <div class="field custom-field-right">
                            <?php echo $this->getBalanceFormat($_giftCard) ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-6">
                    <div class="fields">
                        <div class="field custom-field">
                            <p><?php echo $this->__('Status') ?></p>
                        </div>
                        <div class="field custom-field-right">
                            <?php echo $this->getStatus($_giftCard) ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="fields">
                        <div class="field custom-field">
                            <p><?php echo $this->__('Added Date') ?></p>
                        </div>
                        <div class="field custom-field-right">
                            <?php echo $this->formatDate($_customerGift->getData('added_date'), 'medium') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-6">
                    <div class="fields">
                        <div class="field custom-field">
                            <p><?php echo $this->__('Expired Date') ?></p>
                        </div>
                        <div class="field custom-field-right">
                            <?php 
                                //Hai.Tran
                                $expired_date = $_giftCard->getData('expired_at');
                                if(!$expired_date) echo $this->__('Permanent');
                                else echo $this->formatDate($expired_date, 'medium');
                            ?>
                            <?php //echo $this->formatDate($_giftCard->getData('expired_at'), 'medium') ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <?php if ($_giftCard->getDescription()): ?>
                        <div class="fields">
                            <div class="field custom-field">
                                <p><?php echo $this->__('Description') ?></p>
                            </div>
                            <div class="field custom-field-right">
                                <?php echo $_giftCard->getDescription() ?>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>


            <?php if ($this->checkSendFriendGiftCard($_giftCard)): ?>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="fields">
                            <div class="field custom-field">
                                <p><?php echo $this->__('Comment') ?></p>
                            </div>
                            <div class="field custom-field-right">
                                <?php echo $this->__('This is your gift to give for %s (%s)',$_giftCard->getRecipientName(), $_giftCard->getRecipientEmail()) ?>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if ($_shipment = $this->getShipmentForGiftCard($_giftCard)): ?>
                    <?php $tracks = $_shipment->getTracksCollection(); ?>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="fields">
                                <div class="field custom-field">
                                    <strong><?php echo $this->__('Check Shipping') ?></strong>
                                </div>
                                <div class="field custom-field-right">
                                    <div>
                                        <a href="<?php echo $this->getUrl('sales/order/shipment', array('order_id' => $_shipment->getOrderId())) ?>" title="<?php echo $this->__('View Shipment') ?>"><?php echo $this->__('View Shipment') ?></a>
                                        |
                                        <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_shipment) ?>','trackshipment','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track the shipment') ?>"><?php echo $this->__('Track the shipment') ?></a>
                                    </div>
                                    <div>
                                    <?php if ($_size = $tracks->count()): ?>
                                        <?php echo $this->__('Tracking Number(s):') ?>
                                        <?php
                                        $i = 1;
                                        foreach($tracks as $track): ?>
                                        <?php if($track->isCustom()): ?>
                                            <?php echo $this->escapeHtml($track->getNumber()) ?>
                                        <?php else: ?>
                                            <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?></a>
                                        <?php endif; ?>
                                        <?php if($i!=$_size): ?>, <?php endif; ?>
                                        <?php $i++;
                                        endforeach; ?>
                                    <?php endif ?>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                <?php endif ?>
            
            <?php endif ?>
        </div>

        <div class="space30"></div>
    </div>

</div>
